{{- if .Values.standalone.enabled }}
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: {{ .Values.standalone.name }}
  namespace: {{ default (include "splunk-enterprise.namespace" . ) .Values.standalone.namespaceOverride }}
{{- with .Values.standalone.additionalLabels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.standalone.replicaCount }}
  replicas: {{ .Values.standalone.replicaCount }}
{{- end }}
{{- with .Values.standalone.appRepo }}
  appRepo: 
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.standalone.smartstore }}
  smartstore:
{{ toYaml .Values.standalone.smartstore | indent 4 }}
{{- end }}
{{- if .Values.existingClusterMaster }}
  clusterMasterRef:
    name: {{ .Values.existingClusterMaster.name }}
  {{- if .Values.existingClusterMaster.namespace }}
    namespace: {{ .Values.existingClusterMaster.namespace }}
  {{- end }}
{{- else if .Values.clusterMaster.enabled }}
  clusterMasterRef:
    name: {{ .Values.clusterMaster.name }}
  {{- if .Values.clusterMaster.namespaceOverride }}
    namespace: {{ .Values.clusterMaster.namespaceOverride }}
  {{- end }}
{{- end }}
{{- if .Values.existingLicenseMaster }}
  licenseMasterRef:
    name: {{ .Values.existingLicenseMaster.name }}
  {{- if .Values.existingLicenseMaster.namespace }}
    namespace: {{ .Values.existingLicenseMaster.namespace }}
  {{- end }}
{{- else if .Values.licenseMaster.enabled }}
  licenseMasterRef:
    name: {{ .Values.licenseMaster.name }}
  {{- if .Values.licenseMaster.namespaceOverride }}
    namespace: {{ .Values.licenseMaster.namespaceOverride }}
  {{- end }}
{{- end }}
{{- if .Values.existingMonitoringConsole }}
  monitoringConsoleRef:
    name: {{ .Values.existingMonitoringConsole.name }}
  {{- if .Values.existingMonitoringConsole.namespace }}
    namespace: {{ .Values.existingMonitoringConsole.namespace }}
  {{- end }}
{{- else if .Values.monitoringConsole.enabled }}
  monitoringConsoleRef:
    name: {{ .Values.monitoringConsole.name }}
  {{- if .Values.monitoringConsole.namespaceOverride }}
    namespace: {{ .Values.monitoringConsole.namespaceOverride }}
  {{- end }}
{{- end }}
{{- if .Values.image.repository }}
  image: {{ .Values.image.repository }}
{{- end }}
{{- if .Values.image.imagePullPolicy }}
  imagePullPolicy: {{ .Values.image.imagePullPolicy }}
{{- end }}
{{- with .Values.image.imagePullSecrets }}
  imagePullSecrets:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.standalone.volumes }}      
  volumes:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if .Values.standalone.licenseUrl }}
  licenseUrl: {{ .Values.standalone.licenseUrl }}
{{- end }}
{{- if .Values.standalone.defaultsUrl }}
  defaultsUrl: {{ .Values.standalone.defaultsUrl }}
{{- end }}
{{- if .Values.standalone.defaults }}
  defaults: |-
{{ toYaml .Values.standalone.defaults | indent 4 }}
{{- end }}
{{- if .Values.standalone.defaultsUrlApps }}
  defaultsUrlApps: {{ .Values.standalone.defaultsUrlApps }}
{{- end }}
{{- with .Values.standalone.extraEnv }}
  extraEnv:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.standalone.livenessInitialDelaySeconds }}
  livenessInitialDelaySeconds: {{ .Values.standalone.livenessInitialDelaySeconds }}
{{- end }}
{{- if .Values.standalone.readinessInitialDelaySeconds }}
  readinessInitialDelaySeconds: {{ .Values.standalone.readinessInitialDelaySeconds }}
{{- end }}
{{- with .Values.standalone.etcVolumeStorageConfig }}
  etcVolumeStorageConfig:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.standalone.varVolumeStorageConfig }}
  varVolumeStorageConfig:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.standalone.resources }}
  resources:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if .Values.standalone.serviceAccount }}
  serviceAccount: {{ .Values.standalone.serviceAccount }}
{{- end }}
{{- with .Values.standalone.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.standalone.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
